### ISSUE TITLE
Error on building Samsung a12

### ISSUE THREAD

**Issue by edward0181** [mohammad92/platform_manifest_twrp_aosp#1]
Newest error I'm getting:

`
FAILED: out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
Outputs: out/soong/build.ninja
Error: exited with code: 1
Command: out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
Output:
�[31merror:�[0m frameworks/base/core/res/Android.bp:49:1: module "framework-res-package-jar" variant "android_common": path dependency ":framework-res{.export-package.apk}": unsupported module reference tag ".export-package.apk"

`

**Comment by mohammad92** [comment]
Comment out the "framework-res-package-jar" in frameworks/base/core/res/Android.bp

**Comment by edward0181** [comment]
Thanks. Then it ends in<

[ 99% 281/282] finishing build rules ...
vendor/twrp/build/tasks/kernel.mk:122: warning: ***************************************************************
vendor/twrp/build/tasks/kernel.mk:123: warning: * Using prebuilt kernel binary instead of source              *
vendor/twrp/build/tasks/kernel.mk:124: warning: * THIS IS DEPRECATED, AND IS NOT ADVISED.                     *
vendor/twrp/build/tasks/kernel.mk:125: warning: * Please configure your device to download the kernel         *
vendor/twrp/build/tasks/kernel.mk:126: warning: * source repository to          vendor/twrp/build/tasks/kernel.mk:127: warning: * for more information                                        *                                                 vendor/twrp/build/tasks/kernel.mk:128: warning: ***************************************************************
ninja: no work to do.                                                           
#### build completed successfully (06:08 (mm:ss)) ####                          twrp@h2701744:~/android$
>

**Comment by edward0181** [comment]
Forgot to tell. Thanks for the help. Really stuck on this bloody phone
